import { execFile, spawn, type ChildProcess } from "node:child_process"
import fs from "node:fs/promises"
import path from "node:path"
import { promisify } from "node:util"
import type { Db } from "../db/index.js"
import type { Env } from "../env.js"
import { ensureComponentPreviewWorkspace } from "./component-preview-workspace.js"
import { killDevProcessTree } from "./process-tree.js"
import {
  getComponentPreviewAllowedHosts,
  getComponentPreviewBasePath,
  getComponentPreviewInternalUrl,
  getComponentPreviewPublicUrl,
  resolveComponentPreviewDir,
} from "./paths.js"

const execFileAsync = promisify(execFile)

type DevStatus = "stopped" | "starting" | "running" | "failed"

let devProcess: ChildProcess | null = null
let devStatus: DevStatus = "stopped"
let devError: string | null = null
let activeEnv: Env | null = null
let restartInFlight: Promise<{ status: DevStatus; url: string | null; error: string | null }> | null =
  null

function getInternalProbeUrl(env: Env) {
  return getComponentPreviewInternalUrl(
    env.COMPONENT_PREVIEW_DEV_HOST,
    env.COMPONENT_PREVIEW_DEV_PORT,
    env.COMPONENT_PREVIEW_PUBLIC_URL,
  )
}

function getPublicBaseUrl(env: Env) {
  return getComponentPreviewPublicUrl(
    env.COMPONENT_PREVIEW_DEV_HOST,
    env.COMPONENT_PREVIEW_DEV_PORT,
    env.COMPONENT_PREVIEW_PUBLIC_URL,
  )
}

async function ensureNpmInstall(previewDir: string) {
  try {
    await fs.access(path.join(previewDir, "node_modules"))
  } catch {
    await execFileAsync("npm", ["install"], {
      cwd: previewDir,
      shell: true,
      windowsHide: true,
    })
  }
}

function htmlHasRootViteAssets(html: string) {
  return (
    html.includes('src="/@vite/') ||
    html.includes("src='/@vite/") ||
    html.includes('src="/src/') ||
    html.includes("src='/src/") ||
    html.includes('src="/@id/') ||
    html.includes("src='/@id/")
  )
}

/**
 * Probe the base URL. Reject servers that still emit root Vite assets
 * (`/@vite/client`) — those are stale Astro instances started without `base`.
 */
async function isPreviewServerRunning(url: string, basePath = "/") {
  try {
    const response = await fetch(url, { method: "GET", redirect: "follow" })
    if (!response.ok) {
      return false
    }

    if (basePath === "/") {
      return true
    }

    const html = await response.text()
    if (htmlHasRootViteAssets(html)) {
      return false
    }

    return true
  } catch {
    return false
  }
}

async function freePreviewPort(port: number) {
  if (process.platform === "win32") {
    return
  }

  try {
    await execFileAsync("fuser", ["-k", `${port}/tcp`], {
      shell: true,
      windowsHide: true,
    })
  } catch {
    // nothing listening, or fuser unavailable
  }
}

/**
 * Bake runtime proxy settings into astro.config so Astro cannot miss env vars.
 */
async function writePreviewAstroConfig(
  previewDir: string,
  input: {
    basePath: string
    publicUrl: string
    allowedHosts: true | string[]
  },
) {
  const allowedHostsLiteral =
    input.allowedHosts === true
      ? "true"
      : `[${input.allowedHosts.map((host) => JSON.stringify(host)).join(", ")}]`
  const behindProxy = Boolean(input.publicUrl)
  const baseLiteral = JSON.stringify(input.basePath)

  const contents = `// Generated by cms-backend — do not edit by hand
import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  base: ${baseLiteral},
  devToolbar: { enabled: false },
  server: {
    allowedHosts: ${allowedHostsLiteral},
  },
  vite: {
    plugins: [tailwindcss()],
    define: {
      "import.meta.env.CMS_COMPONENT_PREVIEW": JSON.stringify(true),
    },
    server: {
      allowedHosts: ${allowedHostsLiteral},
      ${behindProxy ? "hmr: false," : ""}
    },
  },
});
`

  await fs.writeFile(path.join(previewDir, "astro.config.mjs"), contents, "utf8")
}

async function clearStaleAstroDevLock(previewDir: string, url: string, basePath: string) {
  if (await isPreviewServerRunning(url, basePath)) {
    return
  }

  const devJsonPath = path.join(previewDir, ".astro", "dev.json")

  try {
    await fs.access(devJsonPath)
  } catch {
    return
  }

  try {
    await execFileAsync("npx", ["astro", "dev", "stop"], {
      cwd: previewDir,
      shell: true,
      windowsHide: true,
    })
  } catch {
    try {
      await fs.unlink(devJsonPath)
    } catch {
      // ignore
    }
  }
}

async function waitForDevServer(url: string, basePath: string, timeoutMs = 90_000) {
  const startedAt = Date.now()

  while (Date.now() - startedAt < timeoutMs) {
    if (await isPreviewServerRunning(url, basePath)) {
      return
    }

    await new Promise((resolve) => setTimeout(resolve, 500))
  }

  throw new Error("Component preview dev server failed to start in time")
}

export function getComponentDevServerStatus() {
  return {
    status: devStatus,
    url: activeEnv ? getPublicBaseUrl(activeEnv) : null,
    error: devError,
  }
}

export async function stopComponentDevServer() {
  if (devProcess) {
    await killDevProcessTree(devProcess)
    devProcess = null
  }

  if (activeEnv) {
    const previewDir = resolveComponentPreviewDir(activeEnv.COMPONENT_PREVIEW_DIR)
    const port = activeEnv.COMPONENT_PREVIEW_DEV_PORT

    try {
      await execFileAsync("npx", ["astro", "dev", "stop"], {
        cwd: previewDir,
        shell: true,
        windowsHide: true,
      })
    } catch {
      // ignore
    }

    await freePreviewPort(port)
  }

  devStatus = "stopped"
  devError = null

  return getComponentDevServerStatus()
}

export async function ensureComponentDevServer(env: Env, db: Db) {
  activeEnv = env
  const internalUrl = getInternalProbeUrl(env)
  const publicUrl = getPublicBaseUrl(env)
  const port = env.COMPONENT_PREVIEW_DEV_PORT
  const basePath = getComponentPreviewBasePath(env.COMPONENT_PREVIEW_PUBLIC_URL)
  const publicUrlForAstro = env.COMPONENT_PREVIEW_PUBLIC_URL?.trim().replace(/\/$/, "") || ""
  const allowedHostsConfig = getComponentPreviewAllowedHosts(
    env.COMPONENT_PREVIEW_PUBLIC_URL,
    env.COMPONENT_PREVIEW_ALLOWED_HOSTS,
  )
  const allowedHostsEnvValue =
    allowedHostsConfig === true ? "true" : allowedHostsConfig.join(",")

  if (devStatus === "running" && devProcess) {
    if (await isPreviewServerRunning(internalUrl, basePath)) {
      return { ...getComponentDevServerStatus(), url: publicUrl }
    }
    await stopComponentDevServer()
  }

  if (await isPreviewServerRunning(internalUrl, basePath)) {
    devStatus = "running"
    devError = null
    return { ...getComponentDevServerStatus(), url: publicUrl }
  }

  if (devStatus === "starting") {
    await waitForDevServer(internalUrl, basePath)
    devStatus = "running"
    return { ...getComponentDevServerStatus(), url: publicUrl }
  }

  await ensureComponentPreviewWorkspace(db, env)
  const previewDir = resolveComponentPreviewDir(env.COMPONENT_PREVIEW_DIR)
  await ensureNpmInstall(previewDir)
  await writePreviewAstroConfig(previewDir, {
    basePath,
    publicUrl: publicUrlForAstro,
    allowedHosts: allowedHostsConfig === true || allowedHostsConfig.length > 0 ? allowedHostsConfig : true,
  })
  await clearStaleAstroDevLock(previewDir, internalUrl, basePath)
  await freePreviewPort(port)
  await new Promise((resolve) => setTimeout(resolve, 400))

  devStatus = "starting"
  devError = null

  const devArgs = ["run", "dev", "--", "--port", String(port), "--host"]
  if (basePath !== "/") {
    devArgs.push("--base", basePath)
  }
  if (allowedHostsConfig === true || allowedHostsConfig.length === 0) {
    // empty list + public URL still needs hosts; writePreviewAstroConfig used `true`
    devArgs.push("--allowed-hosts", "true")
  } else {
    devArgs.push("--allowed-hosts", allowedHostsConfig.join(","))
  }

  devProcess = spawn("npm", devArgs, {
    cwd: previewDir,
    shell: true,
    windowsHide: true,
    stdio: "pipe",
    env: {
      ...process.env,
      COMPONENT_PREVIEW_BASE: basePath,
      ...(publicUrlForAstro ? { COMPONENT_PREVIEW_PUBLIC_URL: publicUrlForAstro } : {}),
      ...(allowedHostsEnvValue
        ? {
            COMPONENT_PREVIEW_ALLOWED_HOSTS: allowedHostsEnvValue,
            __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: allowedHostsEnvValue,
          }
        : {
            COMPONENT_PREVIEW_ALLOWED_HOSTS: "true",
            __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "true",
          }),
    },
  })

  devProcess.on("exit", (code) => {
    if (devStatus !== "stopped") {
      devStatus = "failed"
      devError = `Dev server exited with code ${code ?? "unknown"}`
    }
    devProcess = null
  })

  devProcess.stderr?.on("data", (chunk: Buffer) => {
    const message = chunk.toString()
    if (message.toLowerCase().includes("error")) {
      devError = message.trim()
    }
  })

  try {
    await waitForDevServer(internalUrl, basePath)
    devStatus = "running"
    devError = null
  } catch (error) {
    devStatus = "failed"
    devError = error instanceof Error ? error.message : "Failed to start dev server"
    if (devProcess) {
      await killDevProcessTree(devProcess)
    }
    devProcess = null
    throw error
  }

  return { ...getComponentDevServerStatus(), url: publicUrl }
}

async function restartComponentDevServer(env: Env, db: Db) {
  activeEnv = env
  const internalUrl = getInternalProbeUrl(env)
  const basePath = getComponentPreviewBasePath(env.COMPONENT_PREVIEW_PUBLIC_URL)

  if (!(await isPreviewServerRunning(internalUrl, basePath)) && devStatus !== "running" && !devProcess) {
    return ensureComponentDevServer(env, db)
  }

  await stopComponentDevServer()
  await new Promise((resolve) => setTimeout(resolve, 800))
  return ensureComponentDevServer(env, db)
}

export async function restartComponentDevServerIfRunning(env: Env, db: Db) {
  if (restartInFlight) {
    return restartInFlight
  }

  restartInFlight = restartComponentDevServer(env, db).finally(() => {
    restartInFlight = null
  })

  return restartInFlight
}

export function buildComponentPreviewUrl(
  env: Env,
  componentSlug: string,
  variantSlug: string,
) {
  const baseUrl = getPublicBaseUrl(env)
  return `${baseUrl}/preview/${encodeURIComponent(componentSlug)}/${encodeURIComponent(variantSlug)}`
}
