import { execFile, spawn, type ChildProcess } from "node:child_process"
import fs from "node:fs/promises"
import path from "node:path"
import { promisify } from "node:util"
import type { Db } from "../db/index.js"
import type { Env } from "../env.js"
import { ensureComponentPreviewWorkspace } from "./component-preview-workspace.js"
import { killDevProcessTree } from "./process-tree.js"
import {
  getComponentPreviewAllowedHosts,
  getComponentPreviewBasePath,
  getComponentPreviewInternalUrl,
  getComponentPreviewPublicUrl,
  resolveComponentPreviewDir,
} from "./paths.js"

const execFileAsync = promisify(execFile)

type DevStatus = "stopped" | "starting" | "running" | "failed"

let devProcess: ChildProcess | null = null
let devStatus: DevStatus = "stopped"
let devError: string | null = null
let activeEnv: Env | null = null
let restartInFlight: Promise<{ status: DevStatus; url: string | null; error: string | null }> | null =
  null

/** Always probe loopback — DEV_HOST may be a public hostname that is not open on the preview port. */
function getInternalProbeUrl(env: Env) {
  return getComponentPreviewInternalUrl(
    "127.0.0.1",
    env.COMPONENT_PREVIEW_DEV_PORT,
    env.COMPONENT_PREVIEW_PUBLIC_URL,
  )
}

function getPublicBaseUrl(env: Env) {
  return getComponentPreviewPublicUrl(
    env.COMPONENT_PREVIEW_DEV_HOST,
    env.COMPONENT_PREVIEW_DEV_PORT,
    env.COMPONENT_PREVIEW_PUBLIC_URL,
  )
}

function resolveAllowedHostsForConfig(
  publicUrl: string,
  allowedHostsConfig: true | string[],
): string[] {
  if (allowedHostsConfig === true) {
    const hosts = new Set<string>(["localhost", "127.0.0.1"])
    try {
      if (publicUrl) {
        hosts.add(new URL(publicUrl).hostname)
      }
    } catch {
      // ignore
    }
    return [...hosts]
  }

  return allowedHostsConfig.length > 0 ? allowedHostsConfig : ["localhost", "127.0.0.1"]
}

async function ensureNpmInstall(previewDir: string) {
  try {
    await fs.access(path.join(previewDir, "node_modules"))
  } catch {
    await execFileAsync("npm", ["install"], {
      cwd: previewDir,
      shell: true,
      windowsHide: true,
    })
  }
}

/** Fast readiness: HTTP 200 on the base probe URL (loopback only). */
async function isPreviewServerRunning(url: string) {
  try {
    const response = await fetch(url, { method: "GET", redirect: "follow" })
    return response.ok
  } catch {
    return false
  }
}

async function isGeneratedPreviewConfig(previewDir: string) {
  try {
    const content = await fs.readFile(path.join(previewDir, "astro.config.mjs"), "utf8")
    return content.includes("Generated by cms-backend") && content.includes("hmr: false")
  } catch {
    return false
  }
}

async function freePreviewPort(port: number) {
  if (process.platform === "win32") {
    return
  }

  try {
    await execFileAsync("fuser", ["-k", `${port}/tcp`], {
      shell: true,
      windowsHide: true,
    })
  } catch {
    // nothing listening, or fuser unavailable
  }
}

async function writePreviewAstroConfig(
  previewDir: string,
  input: {
    basePath: string
    publicUrl: string
    allowedHosts: string[]
  },
) {
  const allowedHostsLiteral = `[${input.allowedHosts.map((host) => JSON.stringify(host)).join(", ")}]`
  const behindProxy = Boolean(input.publicUrl)
  const baseLiteral = JSON.stringify(input.basePath)

  const contents = `// Generated by cms-backend — do not edit by hand
import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  base: ${baseLiteral},
  devToolbar: { enabled: false },
  server: {
    allowedHosts: ${allowedHostsLiteral},
  },
  vite: {
    plugins: [tailwindcss()],
    define: {
      "import.meta.env.CMS_COMPONENT_PREVIEW": JSON.stringify(true),
    },
    server: {
      allowedHosts: ${allowedHostsLiteral},
      ${behindProxy ? "hmr: false," : ""}
    },
  },
});
`

  await fs.writeFile(path.join(previewDir, "astro.config.mjs"), contents, "utf8")
}

async function clearStaleAstroDevLock(previewDir: string, url: string) {
  if (await isPreviewServerRunning(url)) {
    return
  }

  const devJsonPath = path.join(previewDir, ".astro", "dev.json")

  try {
    await fs.access(devJsonPath)
  } catch {
    return
  }

  try {
    await execFileAsync("npx", ["astro", "dev", "stop"], {
      cwd: previewDir,
      shell: true,
      windowsHide: true,
    })
  } catch {
    try {
      await fs.unlink(devJsonPath)
    } catch {
      // ignore
    }
  }
}

async function waitForDevServer(url: string, timeoutMs = 45_000) {
  const startedAt = Date.now()

  while (Date.now() - startedAt < timeoutMs) {
    if (await isPreviewServerRunning(url)) {
      return
    }

    await new Promise((resolve) => setTimeout(resolve, 400))
  }

  throw new Error("Component preview dev server failed to start in time")
}

export function getComponentDevServerStatus() {
  return {
    status: devStatus,
    url: activeEnv ? getPublicBaseUrl(activeEnv) : null,
    error: devError,
  }
}

export async function stopComponentDevServer() {
  if (devProcess) {
    await killDevProcessTree(devProcess)
    devProcess = null
  }

  if (activeEnv) {
    const previewDir = resolveComponentPreviewDir(activeEnv.COMPONENT_PREVIEW_DIR)
    const port = activeEnv.COMPONENT_PREVIEW_DEV_PORT

    try {
      await execFileAsync("npx", ["astro", "dev", "stop"], {
        cwd: previewDir,
        shell: true,
        windowsHide: true,
      })
    } catch {
      // ignore
    }

    await freePreviewPort(port)
  }

  devStatus = "stopped"
  devError = null

  return getComponentDevServerStatus()
}

export async function ensureComponentDevServer(env: Env, db: Db) {
  activeEnv = env
  const internalUrl = getInternalProbeUrl(env)
  const publicUrl = getPublicBaseUrl(env)
  const port = env.COMPONENT_PREVIEW_DEV_PORT
  const basePath = getComponentPreviewBasePath(env.COMPONENT_PREVIEW_PUBLIC_URL)
  const publicUrlForAstro = env.COMPONENT_PREVIEW_PUBLIC_URL?.trim().replace(/\/$/, "") || ""
  const allowedHostsConfig = getComponentPreviewAllowedHosts(
    env.COMPONENT_PREVIEW_PUBLIC_URL,
    env.COMPONENT_PREVIEW_ALLOWED_HOSTS,
  )
  const allowedHostsList = resolveAllowedHostsForConfig(publicUrlForAstro, allowedHostsConfig)
  const allowedHostsEnvValue = allowedHostsList.join(",")

  if (devStatus === "running" && devProcess) {
    const previewDirForCheck = resolveComponentPreviewDir(env.COMPONENT_PREVIEW_DIR)
    if (
      (await isGeneratedPreviewConfig(previewDirForCheck)) &&
      (await isPreviewServerRunning(internalUrl))
    ) {
      return { ...getComponentDevServerStatus(), url: publicUrl }
    }
    await stopComponentDevServer()
  }

  const previewDirEarly = resolveComponentPreviewDir(env.COMPONENT_PREVIEW_DIR)
  if (
    (await isGeneratedPreviewConfig(previewDirEarly)) &&
    (await isPreviewServerRunning(internalUrl))
  ) {
    devStatus = "running"
    devError = null
    return { ...getComponentDevServerStatus(), url: publicUrl }
  }

  if (devStatus === "starting") {
    await waitForDevServer(internalUrl)
    devStatus = "running"
    return { ...getComponentDevServerStatus(), url: publicUrl }
  }

  await ensureComponentPreviewWorkspace(db, env)
  const previewDir = resolveComponentPreviewDir(env.COMPONENT_PREVIEW_DIR)
  await ensureNpmInstall(previewDir)
  await writePreviewAstroConfig(previewDir, {
    basePath,
    publicUrl: publicUrlForAstro,
    allowedHosts: allowedHostsList,
  })
  await clearStaleAstroDevLock(previewDir, internalUrl)
  await freePreviewPort(port)
  await new Promise((resolve) => setTimeout(resolve, 400))

  devStatus = "starting"
  devError = null

  const devArgs = ["run", "dev", "--", "--port", String(port), "--host", "--allowed-hosts", allowedHostsEnvValue]
  if (basePath !== "/") {
    devArgs.push("--base", basePath)
  }

  let startupLog = ""

  devProcess = spawn("npm", devArgs, {
    cwd: previewDir,
    shell: true,
    windowsHide: true,
    stdio: "pipe",
    env: {
      ...process.env,
      COMPONENT_PREVIEW_BASE: basePath,
      ...(publicUrlForAstro ? { COMPONENT_PREVIEW_PUBLIC_URL: publicUrlForAstro } : {}),
      COMPONENT_PREVIEW_ALLOWED_HOSTS: allowedHostsEnvValue,
      __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: allowedHostsEnvValue,
    },
  })

  devProcess.on("exit", (code) => {
    if (devStatus !== "stopped") {
      devStatus = "failed"
      devError = `Dev server exited with code ${code ?? "unknown"}`
    }
    devProcess = null
  })

  const appendLog = (chunk: Buffer) => {
    startupLog += chunk.toString()
    if (startupLog.length > 4000) {
      startupLog = startupLog.slice(-4000)
    }
    const message = chunk.toString()
    if (message.toLowerCase().includes("error")) {
      devError = message.trim()
    }
  }

  devProcess.stderr?.on("data", appendLog)
  devProcess.stdout?.on("data", appendLog)

  try {
    await waitForDevServer(internalUrl)
    devStatus = "running"
    devError = null
  } catch (error) {
    devStatus = "failed"
    const timeoutMessage = error instanceof Error ? error.message : "Failed to start dev server"
    devError = startupLog.trim()
      ? `${timeoutMessage}\n\nAstro output:\n${startupLog.trim()}`
      : timeoutMessage
    if (devProcess) {
      await killDevProcessTree(devProcess)
    }
    devProcess = null
    throw new Error(devError)
  }

  return { ...getComponentDevServerStatus(), url: publicUrl }
}

async function restartComponentDevServer(env: Env, db: Db) {
  activeEnv = env
  const internalUrl = getInternalProbeUrl(env)

  if (!(await isPreviewServerRunning(internalUrl)) && devStatus !== "running" && !devProcess) {
    return ensureComponentDevServer(env, db)
  }

  await stopComponentDevServer()
  await new Promise((resolve) => setTimeout(resolve, 800))
  return ensureComponentDevServer(env, db)
}

export async function restartComponentDevServerIfRunning(env: Env, db: Db) {
  if (restartInFlight) {
    return restartInFlight
  }

  restartInFlight = restartComponentDevServer(env, db).finally(() => {
    restartInFlight = null
  })

  return restartInFlight
}

export function buildComponentPreviewUrl(
  env: Env,
  componentSlug: string,
  variantSlug: string,
) {
  const baseUrl = getPublicBaseUrl(env)
  return `${baseUrl}/preview/${encodeURIComponent(componentSlug)}/${encodeURIComponent(variantSlug)}`
}
